### ISSUE TITLE
Can hmdq work for HTC VIVE Focus 3?

### ISSUE THREAD

**Issue by g942407** [risa2000/hmdq#1]
HTC VIVE Focus 3 is an all-in-one VR device. I want to know if I can use hmdq for HTC VIVE Focus 3.
Unlike Oculus Quest 2,  HTC VIVE Focus 3 cannot connect to Windows PC except for basic file transfer function.
hmdq works for Oculus Quest 2. So I wander if hmdq can also work for HTC VIVE Focus 3.

**Comment by risa2000** [comment]
@g942407 `hmdq` only works on PC, which means with headsets, which are connected to PC, and currently supports only two VR runtimes - SteamVR (OpenVR) and Oculus (OVR). Unless you could connect Vive Focus 3 to the PC and make either one of the two runtimes to recognize it, `hmdq` cannot be used.
