### ISSUE TITLE
Are you interested in automatic submissions somewhere?

### ISSUE THREAD

**Issue by Bluscream** [risa2000/hmdq#2]
I am in the process of writing a tool that makes use of hmdq to calculate some values need for patching a game for VR. In any case a output json would be generated by the user. If you're interested in more submissions, i could make our tool ask the user if they want to submit their results to some endpoint you can provide if you're interested in more data for your database. Looking forward to hearing from you and thanks for this awesome tool!

**Comment by risa2000** [comment]
@Bluscream Hi!
I considered an automated process at the beginning and decided against it, for following reasons:
* I need to verify the data manually and if there is a problem clarify it with the submitter.
* The data processing (web pages generation) while being an automated process also requires a verification.
* If I already have data for a particular headset, I need to decide which data I will use, typically newer is better but not always.

I am not interested in collecting and analyzing statistical data manually (it is time consuming) and doing it programmatically does not seem to be an easy task considering the points I mentioned above. The issues I had to typically solve required clarifications and sometimes help from the submitters and were not something that could be resolved automatically.

At the current rate - few new headsets every several years - I am fine with the manual approach, which also asks more from the submitters than just "pressing a button".

**Comment by Bluscream** [comment]
I see, i'll just keep the output on the user's pc then as a cache if the hmd isn't plugged in at the time where the tool is ran.
